version: "3.8"

services: 
    db:
        image: mysql:5.7.30 # https://hub.docker.com/_/mysql
        command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
        restart: always
        volumes: 
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: "denoblog"
            MYSQL_ROOT_PASSWORD: 63eaQB9wtLqmNBpg
    api:
        build: .
        restart: always
        depends_on: 
            - db
        volumes: 
            - ./:/usr/app
        ports: 
            - 3000:3000
        environment: 
            - DB_HOST=db # this should be identical to the database service name
            - DB_USER=root
            - DB_DATABASE=denoblog
            - DB_PASSWORD=63eaQB9wtLqmNBpg
            - TOKEN_SECRET=QA3GCPvnNO3e6x29dFfzbvIlP8pRNwif
